name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

        # See gradle file for difference between downloaders
      - name: Build and run Tests
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            ./gradlew check --stacktrace -Ddownloader=REAL
          else
            ./gradlew check --stacktrace -Ddownloader=MOCK
          fi
