name: CI

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - dev
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      - name: Build and run Tests
        run: |
          if [[ $GITHUB_EVENT_NAME == 'schedule' ]]; then
            echo real
          else
            echo mock
            ./gradlew check --stacktrace -Ddownloader=MOCK
          fi